### PR TITLE
Online GIFT-Simulator

### PR DESCRIPTION
**Pull request by leukipp**
An online GIFT-Simulator that runs independent of the programming language used:
[https://leukipp.github.io/xmastree2021/simulator/](https://leukipp.github.io/xmastree2021/simulator/)

A procedural tree is rendered and light coordinates/animation frames can be loaded from url`s or local csv files.
GitHub pages can be used to host the static scripts, as everything runs on the client side.

### CODE REVIEW

**Comment by d-albrecht** [comment]
any chance to make black LEDs actually black? The animation I tested on your simulator has fading colors and as soon as they are completely faded black they switch white. Not ideal, to evaluate the visual quality of my animation. I hope that Matt's tree won't do this, too.

Still, awesome simulator!

**Comment by leukipp** [comment]
> any chance to make black LEDs actually black? The animation I tested on your simulator has fading colors and as soon as they are completely faded black they switch white.

I have made some improvements such that the leds are rendered as light sources. It should be much clearer now which leds are active.

You can have a look at your animation, here:
[https://leukipp.github.io/xmastree2021/simulator/#animations=https://raw.githubusercontent.com/d-albrecht/XMas-Tree-Explosions/main/explosions.csv](https://leukipp.github.io/xmastree2021/simulator/#animations=https://raw.githubusercontent.com/d-albrecht/XMas-Tree-Explosions/main/explosions.csv)

**Comment by Knarf7474** [comment]
I have tested my effect in you simulator, it looks good.
The default tree is a bit dense at the top, making the effect a bit harder to see.
But nice work!

**Comment by d-albrecht** [comment]
if you bring a lot of patience, this looks quite good. But apparently your simulator got a lot laggier than when I first tried it out. Whenever I select one of the drop-downs or color-pickers these dialogs don't show up immediately but at first nothing happens. If I try to switch tabs while some dialog tries to open, the browser takes an eternity to switch tabs (roughly a minute) and one cpu core is at max and when it finally switched tabs either the dialog SHOWS UP ON THE NEW TAB (that isn't the simulator) or the dialog shows up right before the browser switches, meaning I have to go back first. Don't know, maybe that's just for me, but my PC is less than two years old and was mostly current (and not lower tier) parts when I built it.

Is it a flaw in the simulator or a feature that the LEDs seem to flicker? I mean, for my animation this looks really good. I'm tempted to include this on purpose.

**Comment by leukipp** [comment]
> But apparently your simulator got a lot laggier than when I first tried it out.

The animation utilizes the GPU as long the hardware and browser supports it.

Which browser do you use and does performance improve if you disable the glow effect? e.g:
[https://leukipp.github.io/xmastree2021/simulator/#tree.visible=false&light.glow=false&loop=true](https://leukipp.github.io/xmastree2021/simulator/#tree.visible=false&light.glow=false&loop=true)

**Comment by d-albrecht** [comment]
These settings are much more smooth.So it must be a system problem. I'm running Waterfox on Linux, so I can't exactly promise that GPU-acceleration is working as intended.

But either way I took your "idea/issue" of flickering LEDs for my animation. See v2 in my repo. Not sure though if this now would look any good if viewed on your simulator as this might be too much flickering. I hope you didn't mind.

See my readme in case you want to include one of my (older) animations as a preset for your simulator.

**Comment by leukipp** [comment]
Project [moved](https://leukipp.github.io/xmastree/files/simulator/):
[app](https://leukipp.github.io/xmastree/files/simulator/)

**Pull request closed without merging**
