### PR TITLE
Christmas Tree Risk: creates a voronoi-like map

### PR DESCRIPTION
**Pull request by benchatt**
Based on 2 < n < 8 starting "nations" taking unclaimed territory. Each "nation" (light color) takes one new territory (light) per turn. When no more turns are likely, the tree resets with a new randomly-generated starting state.

### CODE REVIEW

**Comment by d-albrecht** [comment]
Unless you can further describe how the colors can acquire new lights and how that translates to Voronoi, I can't really see the connection to Voronoi diagrams to be honest (it seems a bit random in which direction each color is expanding in each turn, whereas Voronoi isn't exactly "expanding" in a random direction to determine the borders). And despite the somewhat wide range of possible values for n, both animations use the same n=4, but the idea and the animation are great nonetheless. There is definitely **some** resemblance to Voronoi in the resulting image but quite a few outliers, too.

**Comment by benchatt** [comment]
I'll retry without the "V-word", since that's causing some concern.

**Comment by d-albrecht** [comment]
Now I start to feel actually bad. I'm really not trying to discourage each and everyone with my comments. And this isn't the first pull request that gets closed unmerged just for one of my comments. To make this crystal clear: I'm no authority in this repository!! Sure, I'm quite active, I "review" each submission because I follow Matt's YouTube channel(s), I like tinkering projects like the LED-tree and when I start caring for a project I invest some time into it (within the bounds of my role as one contributor among several). If I say something, and you don't like it, just ignore me! I explicitly give you permission to do so.

After all, (a) I said that I liked the result even if the title wasn't 100% matching and (b) in this case you probably just could have renamed the file/PR to solve the issue. I mean, you could also change the animation to actually resemble Voronoi, but you don't have to. In fact, while Voronoi has some cool features, and seeing it working out in 3D would be something refreshingly new (always seeing the 2D versions and the comparison to turtle shells can get quite boring), this probably wasn't your idea. And your animation had some charm, too.

Well, to close this up, I hope you don't stop contributing animations entirely.

**Comment by benchatt** [comment]
It's ok, I just redid the pull request as a different PR entirely, I'm not
much of a git expert. Check out PR 49 for my follow up. It's fine! Text
based communication is always tricky.

**Pull request closed without merging**
