### PR TITLE
Rainbow patterns

### PR DESCRIPTION
**Pull request by rendermaniac**
This example is a simple hue colour change based on the distance from the centre of the Christmas tree. This is animated by adding the frame number as an offset.

Note that I just exported 500 frames - I did not bother to make it loopable.

Created using this code:

https://editor.p5js.org/rendermaniac/sketches/OLLuV7vm1

Thanks

Simon
https://www.facebook.com/pihighrockets/

### CODE REVIEW

**Comment by rendermaniac** [comment]
I have added a second rainbow pattern. This uses the angle from the trunk - using atan(z, x) - as the HSL hue. This is then animated with a frame offset and offset up the tree by adding the y value to the angle.

https://editor.p5js.org/rendermaniac/sketches/uy6GT5OUE

The export for this also adds preroll as the pattern needs to get up to speed before export!

**Comment by rendermaniac** [comment]
And one more example just using the y value (plus frame number to animate) the HSL hue value. This gives a rainbow travelling up the tree:

https://editor.p5js.org/rendermaniac/sketches/cpjnhzGV1

**Comment by rendermaniac** [comment]
And a version of rainbow-corkscrew without the y offset so you can see the rainbow clearly spinning around the trunk

**Comment by d-albrecht** [comment]
Isn't (or wasn't) there a Mac mouse animation for "PC is busy" that looks just like the spin animation viewed from the top of the tree? I never used a Mac personally, but that reminded me of something.

Either the rainbow-explosion code used a wrong sign at some point, or I would rather call it implosion. The waves move towards the tree's center, not away from it.

That isn't your fault but the tree has one corner were there are fewer lights, so corkscrew doesn't really look that good in the simulator because for an eighth of each winding essentially there is a hole in the pattern, But if viewed on an actual tree that hides the lights behind it, this might look really good. LeQwasd's simulator just doesn't hide any lights but it's the most comfortable one for me to use. Perhaps I will try this animation on another simulator sometime.

**Comment by oliverdunk** [comment]
Hey again @rendermaniac! Is this one supposed to have the morse code examples from #16?

**Comment by rendermaniac** [comment]
@oliverdunk that's a consequence of commiting the morse example to main, and then branching from it. If you are going to merge both anyway, then don't worry about it. I can separate them into proper branches if you would prefer.

I have rebased this PR with main, so they should be up to date with each other

**Comment by rendermaniac** [comment]
@oliverdunk I have updated to remove files from the other PR

**Comment by rendermaniac** [comment]
I have also renamed explosion to implosion.

Is it worth getting these animations to loop?

**Comment by d-albrecht** [comment]
I guess that is personal preference. If the animation on its own is long enough (such that you might not want to watch it several times) looping will not be your most useful feature. On animations like the heart beat looping is what makes them "look natural". In general I'd say that making rainbow-animations loop-able should be (almost) trivial and usually should make the files smaller. Corkscrew for example goes through 5.5 circles itself, cut it exactly after one circle and it is both way smaller and loop-able.

But officially there is no requirement for the animations to be perfectly looping.

**Comment by oliverdunk** [comment]
This looks great, thanks! The colours look especially great in a simulator, since you can see how the really smooth gradient with the colour definition 😍

**Pull request merged**
