### PR TITLE
Twinkles

### PR DESCRIPTION
**Pull request by rendermaniac**
This is just running Perlin noise through the tree and thresholding the result.

I'm not quite sure if I should leave it like this or make it more complex?

https://editor.p5js.org/rendermaniac/sketches/4v1SoYlF1

### CODE REVIEW

**Comment by rendermaniac** [comment]
Actually - barring any technical issues anyone can see coming up - I will leave it like this.

**Comment by d-albrecht** [comment]
The term "running" through the tree should be taken literally, right? You're not displaying noise on every individual pixel but you generate a noisy pattern that you then move down the z-axis, right? Or is it just coincidence that this animation looks like falling snow? I'm no expert on noise algorithms.

You could integrate other noise sources that determine the colors if you wanted (that would also reduce the overall power consumption if the LEDs weren't full white), but other than that I really like the result you got. And in color this probably wouldn't look snowy anymore.

**Comment by rendermaniac** [comment]
Yes - the pattern is generated using noise(x, y + frame_offset, z) I have converted to a y up orientation, because that it was the library I am visiaulzing with uses and I am more familiar that way up. This is the same as animating "z" in tree coordinates.

I then check if the noise brightness is above 0.55. So this should mean only 45% of the bulbs are lit at any one time (assuming the noise is uniform).

I did try adding multiple noises running at different speeds, with different colours. This does look OK, but gets a little too busy with the low resolution we have. Clearly we need double the number of lights next year!

**Comment by d-albrecht** [comment]
I agree on the low resolution. There were some ideas I had that I just hadn't even started implementing because the output wouldn't have been great. All patterns that just follow some mathematical principle work regardless of the resolution, Animating something specific is harder to get working.

I admit, my comment wasn't really clear. What I meant was to add colors to the dots that then just follow the same path. Not to have several patterns - each with a different color - instead just one global pattern but another noise determines the color. One noise pattern makes the brightness, another the color. To keep this Christmas-y you could limit the colors to red, green, and white. Assuming noise is distributed from -1 to 1, you could define -1 to -0.3 is green, -0.3 to 0.3 is white and 0.3 to 1 is red. The animation speed and such would be the same as now.

But as I said, like the snowy look of the one you got so far.

**Pull request merged**
