### PR TITLE
morse code examples

### PR DESCRIPTION
**Pull request by rendermaniac**
These examples flash the words "Merry Xmas" in morse code.

The easiest to read as Morse code is `morse-xmas-white.csv` which blinks all of the lights together, coloured white. However this is probably also the most power hungry as I think last year you had some problems turning all the lights to full brightness together. 

I am also not sure of the hardware requirements. I have been basing my timings off of 60fps, but I don't know if the Raspberry Pi can drive at this frequency. Slower is probably fine, faster might be a problem for epilectics! (seriously - consider that a warning).

The other 2 files are variations `morse-xmas-random.csv` randomly colors all of the lights each frame. This makes it harder to read the Morse.

And `morse-xmas-twinkle.csv` gives each light a random colour and offsets the animation randomly per light. This is probably the most power friendly version, but also makes it look like random noise rather than being able to see the message.

I created these using P5 - a Javascript version of Processing using their online editor. You can see the original code that generated the animation here:

https://editor.p5js.org/rendermaniac/sketches/QmKh_KZMk

I also verified that I could read all of these files using this Sketch. It also works with the MIT examples:

https://editor.p5js.org/rendermaniac/sketches/yw-tkWRDPy

I will probably post more details on my STEM / rockets facebook page here soon: https://www.facebook.com/pihighrockets/

Thanks for putting all of this together - it's an interesting challenge!

### CODE REVIEW

**Comment by d-albrecht** [comment]
is it intended that long Morse signals change color in between? That confused me a bit in the beginning.

I like the twinkle variance for its random look. That shows how easy it is to create something that looks random to a human eye. Any algorithm surely would detect the pattern easily.

**Comment by rendermaniac** [comment]
At the moment the colour changing is purely based on timing and is constant. So it changes once per dot and dashes are 3 dots. So yes that is expected at the moment. I do admit it does makes it a lot less readable. I might look at fixing it if I can be bothered! It may be easier to track whether the message has changed by comparing to the previous value.

Another extension I was thinking of would be to have distinct dot and dash colours (probably red and green to make it Christmassy). This would probably be easier than making it random as you could use the message array directly (and probably make a dash a different value rather than binary).

**Comment by rendermaniac** [comment]
This is actually annoying me now. I might fix it.

I think there are a lot of possibilities with sensor input. Using the waveform from a microphone might be fun - Christmas Tree Equalizer! Not sure I will hav time myself for this.

**Comment by d-albrecht** [comment]
Well, stuff like your microphone idea might have worked last year, but this year all submissions are static and pre-rendered. You can of course input your favorite Xmas song on your PC and generate the animation to match, but then you have to finalize the csv-file before submission and tell Matt which song to play alongside. And if the song is copy-righted he might just refuse to do so.

**Comment by rendermaniac** [comment]
@d-albrecht I have updated this so the colour doesn't change whilst a light is lit.

**Comment by d-albrecht** [comment]
Yes, the colors don't change anymore while a light is on, but each time the lights **go on** they at first can't agree on a color. [See here](https://leqwasd.github.io/treesim/?url=https://raw.githubusercontent.com/standupmaths/xmastree2021/fb0856fcdb737f46f62ed5a70464fe63be47b5ea/examples/morse-xmas-random.csv)
In the first frame where you light up all LEDs they have all individual have a random color (frame 550 for example), stating with the second frame of each Morse signal they change to one common color (the color of the last LED in the first frame to be precise). And I'm pretty sure that this happens for Morse dots now, too, not only dashes. So, either I didn't noticed the problem with dots before or in some aspect the animation got worse than with the last commit.

**Comment by oliverdunk** [comment]
Hey @rendermaniac! What's your thinking here? Happy to merge this one or we can mark it as a draft if you want to make some tweaks first.

**Comment by rendermaniac** [comment]
@d-albrecht I see what you mean. This is now fixed - I forgot that my pattern was changing at a different rate to the frame rate.

@oliverdunk I think this is good to merge now

**Comment by d-albrecht** [comment]
Hey, I'm by no means the authority to argue against this PR being merged, if you are fine with this version, then I can agree that there is no technical problem anymore, but another small point that you **could** improve is the choice of your random colors. Because [frame 130 of the new version](https://leqwasd.github.io/treesim/?url=https://raw.githubusercontent.com/standupmaths/xmastree2021/74c2e99307a077cbe898bfc92f0f08b594efeaef/examples/morse-xmas-random.csv) is almost not visible at all (especially if you take into account that Matt will not sit in a completely pitch-black room to show off our animations.

For this particular reason, I personally work with random hues exclusively. All my colors are at maximum saturation and value in HSV-color-space. (If you are more familiar with the HSL-color-space, anything with (x, 1, 0.5) is essentially the same as (x, 1, 1) in HSV-space) That still gives you 255*6 different colors to pick from. You can surely be more lax on your S- and L-/V-values, but your animation at frame 130 uses the RGB color 19,15,13 which is **almost** black.

**Comment by rendermaniac** [comment]
@d-albrecht That's a great idea! The colours definitely look better now. I think I'm going to update the lerp example to do this too.

**Comment by rendermaniac** [comment]
@oliverdunk please do merge. I am not planning on making any more changes

**Comment by oliverdunk** [comment]
This looks great! Thanks for your patience - going to go ahead and merge.

P.S: The twinkle one took me a while to figure out, but after reading your description I got it! Love the idea.

**Pull request merged**
