### PR TITLE
Lightning effects! BFS from a random source to target for each RGB color

### PR DESCRIPTION
**Pull request by benchatt**
Breadth-first search based on each light's 10 nearest neighbors (randomly chooses 3 to take as next node), with three searches going concurrently (one each for Red, Green, and Blue).

### CODE REVIEW

**Comment by d-albrecht** [comment]
A few thoughts:
- it's really dark. I know that actual LEDs might look brighter than the simulated ones, but still, you should use a wider color range of what is available (max is 255 per color code; using values between 100 and 150 should still be fine) Keep in mind that you are only addressing one color per search, and you need a bit more power to make one color visible compared to a white LED (if you can see 50/50/50 in the tree, you might need 0/75/0 or more for a pure green LED to be visible, even more so for blue as the human threshold for blue light is higher than for the other two primary colors)
- each graph search is over really quick. Either you should use the new frame-time feature or duplicate each frame or find other ways to make this animation worth viewing. Currently, only an AI with a camera could really appreciate the animation. Other options to make this animation take longer would be: in each frame only let one color do a step the other colors wait, turn each visited node into its own frame (but each color visits one node simultaneously). That's what I could come up with right now, you might have other ideas, too.
- Do the three colors search for a particular node in the tree or are you just traversing the whole tree? If each color has a target, I can't tell from the animation. Maybe highlight the node that the colors are searching for.
- If you made each search take longer, you should reduce the number of searches that you do overall to keep the animation's length within reason.

**Comment by benchatt** [comment]
Thank you for the feedback! I've lengthened the animation significantly, and made sure the target is visible. I also boosted the brightness on all steps. Since I don't have an actual string to test this on, I appreciate this so much.

**Comment by d-albrecht** [comment]
Hey, I don't have such a tree, either. But you can take a look at the plethora of simulators that got linked in this project (some are still in pull-request-state, but work well, too). Either upload your local file or [link the animation file in your repo](https://leqwasd.github.io/treesim/?url=https://raw.githubusercontent.com/standupmaths/xmastree2021/3e3f97d18fa3ec9927ef432ebbbab512877b0140/examples/lightning.csv). I tend to include a direct link to one simulator with each of my pull requests because otherwise every one interested in my animation has to walk through the files and find the direct download link first (which can be a chore, I think I looked at every single submission so far, which meant a lot of clicks through GitHub source trees).

**Comment by benchatt** [comment]
I keep trying to make this nice and running into weird issues, so i'm going to try a completely different effect.

**Pull request closed without merging**
