### PR TITLE
Added Bad Apple

### PR DESCRIPTION
**Pull request by TheAgamer554**
Based on the famous touhou inspired black and white video (https://www.youtube.com/watch?v=FtutLA63Cp8), compared the coordinates of the LEDs to the pixels in the video to replicate it frame by frame. This was made trough a simple script i made in java to convert the images to csv frames for the tree.

The full version didn't fit, as it was larger than the 25 GB permitted on GitHub, so a trimmed version was uploaded. The full version can be found here: [https://drive.google.com/file/d/1Zy1kz8YrNmLj9zM24qycitdXuQlJFZLi/view](https://drive.google.com/file/d/1Zy1kz8YrNmLj9zM24qycitdXuQlJFZLi/view)

### CODE REVIEW

**Comment by avenzi** [comment]
I'm so thrilled that we had the same idea :D
You may want to check out my [PR](https://github.com/standupmaths/xmastree2021/pull/27), which provides a link to my repo that has scripts to convert GIFs into the csv format. I actually did a full version of bad apple that I submitted with that PR, which ended up being about 37MB. You might be able to use my repo to cut down the size of yours as well, if you are interested.

**Comment by TheAgamer554** [comment]
oh lmao, i just used ffmpeg and scanned trough every frame. I did it very lazily over an afternoon in java since that's the lang i was familiar with. Mine was around 27 MB at 30fps

**Comment by avenzi** [comment]
Oh I thought you said it was 25 GB, which is why I offered my repo. Looks like you got it worked out anyway.
I can't wait to see Matt's tree filled with memes :)

**Comment by d-albrecht** [comment]
Hey, you might want to adjust the axes. I'm pretty sure that the image is only visible from the wrong side of the tree (in regards to Matt's camera position). The viewing perspective is outlined here: #21

**Comment by TheAgamer554** [comment]
> Hey, you might want to adjust the axes. I'm pretty sure that the image is only visible from the wrong side of the tree (in regards to Matt's camera position). The viewing perspective is outlined here: #21

yeah, i wrote the entire code without looking at the repo, so i just chose some random coordinates that look good. I will fix it asap, thx for the heads up

**Comment by TheAgamer554** [comment]
for your viewing (and listening) pleasure https://youtu.be/IUReVLqnLDQ

**Comment by d-albrecht** [comment]
Next, someone posts a tool where you input a random YouTube video ID and can download the animation csv... Man, impressive!

Only the resolution isn't optimal, but that's nothing you can influence.

**Comment by oliverdunk** [comment]
Super cool animation and process behind it! Love it!

**Pull request merged**
