### PR TITLE
Add (my) MPTree project to Further Work on README

### PR DESCRIPTION
**Pull request by santiagodg**
I am seeing others come up with similar projects for visualizing/simulating tree light sequences. Should we separate these into their own README section, or directory, or is the "Further Work" section fine?

Apart from that, I'm also waiting for others to upload their sequences to have more random sequences to show since currently I'm only linking to a single one.

### CODE REVIEW

**Comment by d-albrecht** [comment]
Is there any way to debug your simulator? The "random sequence" shows up just fine but my local file won't show any lights turning on. And this exact file worked on other simulators.
[My test file](https://github.com/d-albrecht/XMas-Tree-Explosions/blob/main/explosions.csv) (look at the repo to get an idea for what should show up)

PS: I'm planning on submitting this animation as soon as I have a version that I know is of decent visual quality and we have ANY information on an approximate animation speed as some of last year's submissions showed some strange timings. And this year the timing should in theory be trivial as the RPi is doing the exact same instructions each frame, resulting in pretty consistent frame timings.

**Comment by santiagodg** [comment]
@d-albrecht I noticed your CSV file has lowercase headers. I updated the [simulator](https://santiagodg.github.io/mptree/) to turn all CSV files uppercase before parsing them. Can you please try it out now? Your sequence looks very nice to me!

About the animation timing, the library I used to display the tree is p5.js, which runs at 60 fps by default, so you can get an idea for the speed of your animation.

Also, can I get your permission to use your explosion.csv as a random sequence for my project? I would be giving you credit on the footer and linking to your project.

Thanks!

**Review by sebimoe — APPROVED** [review]
Good idea, I will add my project to the section too

**Comment by d-albrecht** [comment]
Oh shoot. To be completely honest, I never even thought about the possibility, that I'm partially responsible for this issue, too. But frankly, no-one ultimately defined this format in such depths. And all python code not only not interprets the first row and column but outright ignores them. And while I see reasons to actually use the headers for shenanigans like only addressing the LEDs that actually have activity or (see the response to my issue report) change the timings, both in order to reduce file size, all these changes would make the animation file not backwards-compatible anymore, so I don't know whether a simulator should really care for the headers. As I said, there is no clear format, the headers could be any of those: "42r", "42R", "R42", "r42", all of these with "_", "-", "#" in between, instead of "r, g, b" use "a, b, c" or "x, y, z" or "42.1" "42.2" and "42.3", or many more. Really, you don't want to guess what people can come up with. So, if you **want** to interpret the headers, be ready for many fixes. Because ultimately, your simulator will always be more restrictive than the python code in this regard. (Not to say that it wouldn't be worth implementing some of my listed features one way or another.) For example, no-where was an official definition, whether the numbers should be floats from 0 to 1 or 8-bit Integers, either.

I don't doubt (and never had) that your simulator runs at some speed, my concern is that we have no information on **The Tree's** animation speed. The RPi 4 seems to be able to reach 60fps (according to some discussion on the Harvard-repo, or was it 30fps?, see I'm already confused again), Matt doesn't use a RPi 4 as far as we know. So, sure, simulated my animation looks good, but it relies on assumptions on the fps. And while you simulate with 60fps, the animation really was designed for 30fps.

As I now know how this animation looks in general and I'm already in the process of improving the animation further, go ahead and use this sample animation! Quite likely it will never run on Matt's tree anyways if I'm able to reach the quality that I currently target. And therefore, all my current attempts will never be seen again. I have six samples in my repo, just take a look and use what you want. I'd say, don't use all of them, but take the one (or two) that looks best to you. And just link to the base project in order for visitors to find my description and the generating code (and spreadsheets). That also goes to anyone else having a simulator with preset animations. these six samples are free to use (attribution would be nice).

Is it just me, or don't you also find it funny, that there are currently more simulators than animations? And that my sample animation is the stress-test for all (browser-based) simulators? I get it, if I hadn't had this idea for over a year and if I was more familiar with 3D-animations, I'd probably have made a simulator instead myself. But we also have to consider Matt's video. He can't make another trending video just with dozens of simulators. ;)

**Comment by d-albrecht** [comment]
I just added v2 of my animations and updated my readme to reflect the usage of my animations as simulator presets. The six samples of v1 are now officially free to use (still, attribution would be nice).

**Comment by santiagodg** [comment]
Thanks @d-albrecht, will be adding your animation soon! 

You make a great point about not having a spec for the animation files, though I was taking the Harvard files as the true format since they had more examples on their [repo](https://github.com/GSD6338/XmasTree). Their coordinate CSVs have headers: "ID", "X", "Y", "Z". Having headers and the "ID" column would actually be breaking the GIFT format but I find it preferable. Their animation CSVs have headers "FRAME_ID", "R_0", "G_0", "B_0", "R_1", "G_1", "B_1", etc. I figured other people generating animation files would be using the same format as the Harvard examples.

After making my simulator handle those files, I tried using Matt's coordinates, but it broke since he isn't using headers nor the "ID" column, so I fixed it by adding a line of headers "X,Y,Z" to files using his format before parsing because I'm currently using a CSV parser which requires headers. I might change this in the future to ignore headers altogether so there's no future problems with them, thanks.

I also found interesting the fact that there are more simulators than animations at this point! At the time I thought it would be useful for other people to have a cross-platform viewer of their animations. I'm actually not very familiar with 3D animations and renders either, but took it up as a fun project. Just looked up something that could render 3D points in space, rotate the camera, and be embedded in the web, then p5.js came up. This is my first time using it and found it nice.

About making animations, I am working on a project which takes last year's python scripts and generates their respective CSV animations so they could be displayed again. It's turning out to be a hacky solution but if it works, it works. I'll probably be making a PR with that project soon. The problem I have is that in the [video were Matt runs last year's animations](https://youtu.be/v7eHTNm1YtU), @thatmattparker says there is in the order of 60 animations, but looking at [last year's repo](https://github.com/standupmaths/xmastree2020), there are only 15 scripts in the `examples` directory. It would be nice to bring back all scripts to have them in this year's format, even if only new ones are displayed in this year's video.

**Comment by d-albrecht** [comment]
Oh, yeah, csv is an interesting format. For another project I wrote my own little csv parser entirely because (a) I wanted to make it a project with as few as possible external dependencies (because of reasons) and (b) because csv is a powerful still pretty simplistic format. And my parser even handled text fields which are a bit trickier with double quotes and escaped commas and such (only line-breaks inside of text fields wasn't in my scope so I ignored them, I could have done them, too, though). But again, if you want to spend some hours on writing a fairly simple parser, then take csv as your target-format. That's an ideal entry point as it isn't trivial but not too complicated either.

The problem with csv-headers though is that - as I said - no-one defined them for this project. Matt never showed actual csv-animation-files and the Harvard repo is an interesting resource, but when I did my file-output I rather looked into the python-code than any example files. And as the code doesn't care, I defined my format in a way that it is still human-readable but I didn't as much cared for exact upper and lower casing and such. I mean, it's trivial to change this. But again, the code doesn't care, so there is little incentive. (And why should I just blindly follow the masses?!?) And if a simulator can't articulate why it couldn't parse my input, there is no reason for me to try and fiddle around. That the coordinate-file doesn't have a header is clearly an oversight, though. You can't call a file a csv-file without a header! On that one you are right. It needs a header at all, the column names are (rather) free to choose.

I know that for last year Matt got some of the submissions by mail (perhaps because folks didn't wanted to have their work public???) so unless you ask him kindly, you won't have access to about a half of the submissions. But I'm not sure if you would get these submissions even if you asked. If your converter is done soon, you could ask Matt to convert them in his spare time such that both the original python codes and the csv-files never leave his PC. But I remember that half the submissions never ran in the first place, so I'm not so certain how many there actually would be (in addition to the submissions in the repo) that are worth tackling. In theory, converting any python code into csv-files has one small problem. Sure, you only have to hijack the RPi's show function to log the current color codes into some file, but last year's animations where bound to their computational load as their clock. So some of the animations wouldn't have the exact same timings anymore. Which could be a good or bad thing, depending on whether they ran smoothly last year or not. While I don't believe that this was a thing, it is possible that someone intentionally did their computation at specific points in time to extend certain frame times.

**Comment by oliverdunk** [comment]
This is a super simple change and I love the simulator, so I'm going to hit merge!

There was some good discussion in here but as far as I can tell, nothing specific that you need an answer to? Some information on the animation speed is here: https://github.com/standupmaths/xmastree2021/issues/9. For anything else, feel free to open an issue. Matt is keeping an eye on those and I can also pass along anything pressing.

Merging one or more simulators in to the repo may be nice at some point but for now I think the further work section is great.

**Pull request merged**
