### PR TITLE
Country flags and explosion

### PR DESCRIPTION
**Pull request by LuukvanKeeken**
I created an animation that displays flags of European countries on the tree, in alphabetical order. Each display was created by essentially overlaying a flag on the Y-Z plane, and setting each light's colours to the colour of the closest flag image pixel. The depth of the tree, i.e. the lights positions in the x-dimension, had no influence. Therefore, the animation is best viewed perpendicular to the Y-Z plane (so down the positive x-axis). As the tree is not rectangular, the top-left and top-right sections of the flags are not displayed on the tree. Unsurprisingly, flags with detailed imagery don't come into their own due to the low resolution, but most the more "simple" flags are quite easy to recognise.
I started out creating an animation for all of the world's flags, but the CSV file became too large for GitHub.

The scripts used in generating the CSV files can be found here: https://github.com/LuukvanKeeken/Country-Flags-Christmas-Tree. There it can also be seen which flags were used, and the order they appear in in the animation, by looking in the ```images_europe``` folder.

### CODE REVIEW

**Comment by oliverdunk** [comment]
Hey @LuukvanKeeken! This is super cool.

Before I merge - is the file size just because of showing the flags for multiple frames do you think? It feels bad to add an 80MB file so I'm wondering if there's anything more than can be done there 🤔

**Comment by LuukvanKeeken** [comment]
Hi @oliverdunk! Yes, the large file size is primarily caused by the amount of frames that each flag is displayed. I assumed that the frame rate would be about 60 frames per second. I found 3 seconds of display time for each flag to be adequate, so each flag gets 180 frames. I could decrease the amount of frames per flag, but that would also shorten the display time if the frame rate is kept the same. If the person using this animation eventually has control over the frame rate, then decreasing the amount of frames would be fine.

**Comment by LuukvanKeeken** [comment]
So I could definitely decrease the file size by decreasing the amount of frames, but whether that is a good option depends on whether or not there will be control over the frame rate when using the animation (or otherwise, on what the frame rate will be if it is fixed).

**Comment by LuukvanKeeken** [comment]
I've also created another animation. First, the string of lights represents a fuse that burns up. This leads up to an "explosion" of a coloured sphere that moves from the centre of the tree outwards. 5 different coloured explosions are included. The code can be found at https://github.com/LuukvanKeeken/Explosion-Christmas-Tree.

**Comment by rendermaniac** [comment]
@LuukvanKeeken Could you split the single file into multiple files - with fewer flags per file?

**Comment by LuukvanKeeken** [comment]
The flags animation is now split up into 5 separate files.

**Comment by d-albrecht** [comment]
Assuming the pull request with the improved python code gets through (which I personally see as almost given if the files don't contain major bugs), you could rewrite your flags animation with one frame per flag and just set the FRAME_TIME to whatever interval you use currently. If I'm not mistaken, 3 seconds would just mean to note a frame time of 3000. If the new file is as compact as it would be then, you could even include some extra (shorter) frames that create smooth transitions between the different flags (either a fade to and from black or just a direct linear color change for each pixel).

**Comment by LuukvanKeeken** [comment]
I could definitely make a new version in that case. Is there any news about that change going through @d-albrecht? Also @oliverdunk, do you think the split into 5 separate files is a valid solution? Otherwise I could also remove those from this pull request and leave the other animation that does have a suitable file size.

**Comment by d-albrecht** [comment]
I can't comment on this PR. Neither am I responsible for this repo (as you might know) nor am I able to verify the submitted code (as python isn't one of my strengths and as I don't have such a tree). I can imagine that Matt will test this on actual hardware before this gets merged. Nonetheless could you prepare a file for the likely outcome that it gets merged, just name the file accordingly.

I know that the second question didn't address me, but having smaller files (in form of the five parts) isn't a bad thing at all. I would definitely keep these for now. Matt will probably run all animations, so it likely will not matter whether it's one large file or several smaller ones.

**Comment by oliverdunk** [comment]
Hey @LuukvanKeeken! Thanks for your patience - I've been merging things here in between festivities with the family. The broken down files look great and seem like a good solution. I'm going to go ahead and merge this!

**Comment by leukipp** [comment]
> could definitely make a new version in that case.

In case you have to update the files, would it be possible to split by names. e.g:
- `flags_of_europe_A_to_F.csv` 
- `flags_of_europe_G_to_L.csv` 
- ...

It would be easier to look out for a particular country flag. Love the idea, nice work!

**Comment by LuukvanKeeken** [comment]
That's a great idea @leukipp , thanks for the suggestion!

**Pull request merged**
